trigger:
  batch: true
  branches:
    include:
      - "master"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.61
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - job: Build_and_Publish_Artifact
    pool:
      name: DAS - Continuous Integration Agents
      demands: LATEST_DOTNET_VERSION -equals 3.1
    workspace:
      clean: all

    steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        Contents: |
          azure/**
          src/**
        TargetFolder: '$(build.artifactstagingdirectory)/publish'
        OverWrite: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/publish'
