trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

stages:
  - stage: Build
    jobs:
      - job: Build_and_Publish_Artifact
        pool:
          name: 'DAS - Continuous Integration'

        workspace:
          clean: all

        steps:
          - task: gittools.gitversion-preview.gitversion-task.GitVersion@5
            displayName: GitVersion
            inputs:
              configFilePath: GitVersion.yml

          - template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
            inputs:
              Contents: |
                azure/**
                src/**
              TargetFolder: '$(build.artifactstagingdirectory)/publish'
              OverWrite: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)/publish'