trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

stages:
  - stage: Version
    jobs:
      - job: GitVersion
        pool:
          name: 'Hosted VS2017'

        workspace:
          clean: all

        steps:
          - task: GitVersion@4
            displayName: GitVersion

  - stage: Build
    jobs:
      - job: Build_and_Publish_Artifact
        pool:
          name: 'DAS - Continuous Deployment'

        workspace:
          clean: all

        steps:
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
            inputs:
              Contents: |
                azure/**
                src/**
              TargetFolder: '$(build.artifactstagingdirectory)/publish'
              OverWrite: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)/publish'