trigger:
  batch: true
  branches:
    include:
      - "master"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - job: Build_and_Publish_Artifact
    pool:
      name: DAS - Continuous Integration Agents
      demands: LATEST_DOTNET_VERSION -equals 3.1
    variables:
    - group: BUILD Management Resources
    workspace:
      clean: all

    steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - task: SonarCloudPrepare@1
      displayName: Prepare SonarCloud analysis configuration
      condition: and(succeeded(), or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))
      inputs:
        SonarCloud: ESFA - SonarCloud
        organization: $(SonarCloudOrganisationKey)
        scannerMode: CLI
        configMode: manual
        cliProjectName: "$(Build.DefinitionName)"
        cliProjectKey: ${{ replace(variables['Build.Repository.Name'], '/', '_') }}

    - task: SonarCloudAnalyze@1
      displayName: Run SonarCloud analysis
      condition: and(succeeded(), or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))

    - task: SonarCloudPublish@1
      displayName: Publish SonarCloud analysis results on build summary
      condition: and(succeeded(), or(in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))
      inputs:
        pollingTimeoutSec: '300'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        Contents: |
          azure/**
          src/**
        TargetFolder: '$(build.artifactstagingdirectory)/publish'
        OverWrite: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/publish'
